coreutils: fix #11389 build failure
Fix compilation error due to multiple definition

x86_64-openwrt-linux-musl/bin/ld: lib/libcoreutils.a(strtold.o):(.data+0x0):
multiple definition of `minus_zero'; lib/libcoreutils.a(strtod.o):(.data+0x0):
first defined here
collect2: error: ld returned 1 exit status

Signed-off-by: DENG Qingfang <dengqf6@mail2.sysu.edu.cn>
(cherry picked from commit 6be6e9c7e397662b905af9822c77b4fd20600b88)

Change-Id: Ifdfd02e9d26adb0f136a30b4f228e7cc5b45db7b
Signed-off-by: Sanjeev N <quic_nsanjeev@quicinc.com>