xtables-addons: rtsp: fix compile warning/issue
Fix compile issue with Werror:

nf_conntrack_rtsp.c:667:39: error: implicit declaration of function 'nf_ct_zone' [-Werror=implicit-function-declaration]
   exp_ct = nf_ct_expect_find_get(net, nf_ct_zone(ct), &t);

Fix compile warning:

nf_conntrack_rtsp.c:474:2: warning: enumeration value 'IP_CT_DIR_MAX' not handled in switch [-Wswitch]
  switch (CTINFO2DIR(ctinfo)) {
  ^~~~~~

Signed-off-by: Hans Dedecker <dedeckeh@gmail.com>
(cherry picked from commit d01b62924e13dd609ce177faad89b61170f6155c)

Change-Id: I5134640ab28b373238d96bdb52e121ad946f1d4d
Signed-off-by: Ronghua Zeng <quic_ronghuaz@quicinc.com>